In [1]:
#Solution to Kaggle Taxi Fare Prediction competition
#https://www.kaggle.com/c/new-york-city-taxi-fare-prediction
#Placement: 303/1488

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import os
from tqdm import tqdm
import math
from sklearn.model_selection import train_test_split
from subprocess import call
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [3]:
#inputs
TEST_PATH = 'Data/test.csv'
TRAIN_PATH = 'Data/train_1mln.csv'
#TRAIN_PATH = 'Data/train.csv'

In [4]:
#calculate distance between coordinates using Haversine formula ( https://en.wikipedia.org/wiki/Haversine_formula )
def calc_distance(lat1, lon1, lat2, lon2):
    radius = 6371 # km
    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c

    return d

#use apply function to calculate distance
def get_distance(df):
    df['distance'] = df.apply(lambda row: calc_distance(row['pickup_latitude'], 
                                 row['pickup_longitude'], 
                                 row['dropoff_latitude'], 
                                 row['dropoff_longitude']), axis=1)
    return df

#set max distance, drop values above 100km 
def lower_distance(df):
    df = df[df['distance'] < 100]
    return df

In [5]:
#drop missings, unreal values
def clean_data(df):
    df = df.dropna(how = 'any', axis = 'rows')
    df = df[(df['passenger_count'] > 0) & (df['passenger_count'] < 7)]
    df = df[(df['fare_amount'] > 0) & (df['fare_amount'] < 100)]
    df = df[(df['pickup_latitude'] != 0) & (df['pickup_longitude'] != 0) &
                        (df['dropoff_latitude'] != 0) & (df['dropoff_longitude'] != 0)]
    return df

In [6]:
#Extract hour, day, month and year  from datetime
def get_date_features(df):
    df['hour'] = df.pickup_datetime.dt.hour
    df['dayofweek'] = df.pickup_datetime.dt.dayofweek
    df['month'] = df.pickup_datetime.dt.month
    df['year'] = df.pickup_datetime.dt.year
    
    return df

In [9]:
#Define bounding box - max cords extracted from test set
BB = (-74.55, -72.75, 40.45, 41.85)
    
# Select trips only within boundingbox - max cordinates values extracted from test_set
def select_within_boundingbox(df, BB):
    df = df[(df.pickup_longitude >= BB[0]) & (df.pickup_longitude <= BB[1]) & \
           (df.pickup_latitude >= BB[2]) & (df.pickup_latitude <= BB[3]) & \
           (df.dropoff_longitude >= BB[0]) & (df.dropoff_longitude <= BB[1]) & \
           (df.dropoff_latitude >= BB[2]) & (df.dropoff_latitude <= BB[3])]
    return df


#Remove incorrect values - locations on water
#This trick is taken from https://www.kaggle.com/breemen/nyc-taxi-fare-data-exploration
def remove_datapoints_from_water(df):
    def lonlat_to_xy(longitude, latitude, dx, dy, BB):
        return (dx*(longitude - BB[0])/(BB[1]-BB[0])).astype('int'), \
               (dy - dy*(latitude - BB[2])/(BB[3]-BB[2])).astype('int')

    # read nyc mask and turn into boolean map with
    # land = True, water = False
    nyc_mask = plt.imread('Data/nyc_mask.png')[:,:,0] > 0.9
    
    # calculate for each lon,lat coordinate the xy coordinate in the mask map
    pickup_x, pickup_y = lonlat_to_xy(df.pickup_longitude, df.pickup_latitude, 
                                      nyc_mask.shape[1], nyc_mask.shape[0], BB)
    dropoff_x, dropoff_y = lonlat_to_xy(df.dropoff_longitude, df.dropoff_latitude, 
                                      nyc_mask.shape[1], nyc_mask.shape[0], BB)    
    # calculate boolean index
    idx = nyc_mask[pickup_y, pickup_x] & nyc_mask[dropoff_y, dropoff_x]
    df = df[idx]
    # return only datapoints on land
    return df

In [10]:
%%time

traintypes = {'fare_amount': 'float32',
              'pickup_datetime': 'str', 
              'pickup_longitude': 'float32',
              'pickup_latitude': 'float32',
              'dropoff_longitude': 'float32',
              'dropoff_latitude': 'float32',
              'passenger_count': 'uint8'}

cols = list(traintypes.keys())
chunksize = 1000 
df_list = [] # list to hold the batch dataframe

for df_chunk in tqdm(pd.read_csv(TRAIN_PATH, usecols=cols, dtype=traintypes, chunksize=chunksize)):
     
    # Neat trick from https://www.kaggle.com/btyuhas/bayesian-optimization-with-xgboost
    # Using parse_dates would be much slower!
    df_chunk['pickup_datetime'] = df_chunk['pickup_datetime'].str.slice(0, 16)
    df_chunk['pickup_datetime'] = pd.to_datetime(df_chunk['pickup_datetime'], utc=True, format='%Y-%m-%d %H:%M')
    
    df_chunk = clean_data(df_chunk)
    df_chunk = get_date_features(df_chunk)
    df_chunk = get_distance(df_chunk)
    df_chunk = lower_distance(df_chunk)
    df_chunk = select_within_boundingbox(df_chunk, BB)
    df_chunk = remove_datapoints_from_water(df_chunk)
    df_chunk = df_chunk.drop('pickup_datetime', axis=1)
    
    X = df_chunk.drop(["fare_amount"],axis=1)
    y = df_chunk.fare_amount
    
    
    
    
    df_list.append(df_chunk)

66it [00:09,  7.32it/s]

KeyboardInterrupt:


55it [27:55, 30.46s/it]
IndexError                                Traceback (most recent call last)
<timed exec> in <module>()

<ipython-input-12-d5092148ffb0> in remove_datapoints_from_water(df)
     16                                       nyc_mask.shape[1], nyc_mask.shape[0], BB)    
     17     # calculate boolean index
---> 18     idx = nyc_mask[pickup_y, pickup_x] & nyc_mask[dropoff_y, dropoff_x]
     19     df = df[idx]
     20     # return only datapoints on land

IndexError: index 1262 is out of bounds for axis 0 with size 1262

In [16]:
# Merge all dataframes into one dataframe
df = pd.concat(df_list)

# Delete the dataframe list to release memory
del df_list

# See what we have loaded
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52878537 entries, 0 to 55423855
Data columns (total 11 columns):
fare_amount          float32
pickup_longitude     float32
pickup_latitude      float32
dropoff_longitude    float32
dropoff_latitude     float32
passenger_count      uint8
hour                 int64
dayofweek            int64
month                int64
year                 int64
distance             float64
dtypes: float32(5), float64(1), int64(4), uint8(1)
memory usage: 3.4 GB

In [7]:
def XGBoost_first_iter(X_train,X_test,y_train,y_test,num_rounds=1000):
    dtrain = xgb.DMatrix(X_train,label=y_train)
    dtest = xgb.DMatrix(X_test,label=y_test)
    xgb_model = xgb.train(params={
            'eval_metric':'rmse',
            'objective':'reg:linear',
            'max_depth': '8',
            'tree_method':'approx'}
            ,dtrain=dtrain,num_boost_round=num_rounds, 
            early_stopping_rounds=20,evals=[(dtest,'test')])
    xgb_model.save_model('taxi_fare_2nd.model')

def XGBoost(X_train,X_test,y_train,y_test,num_rounds=1000):
    dtrain = xgb.DMatrix(X_train,label=y_train)
    dtest = xgb.DMatrix(X_test,label=y_test)
    xgb_model = xgb.train(params={
            'eval_metric':'rmse',
            'objective':'reg:linear',
            'max_depth': '8',
            'tree_method':'approx'}
            ,dtrain=dtrain,num_boost_round=num_rounds, 
            early_stopping_rounds=20,evals=[(dtest,'test')],xgb_model='taxi_fare_2nd.model')
    call(["mv", "taxi_fare_2nd.model taxi_fare_2nd.model.bak"])
    call(["rm", "taxi_fare_2nd.model"])
    xgb_model.save_model('taxi_fare_2nd.model')

In [17]:
df.shape

(52878537, 11)

In [18]:
df.to_csv('52mln_clean.csv')

In [2]:
TRAIN_PATH = '52mln_clean.csv'

In [4]:
def lower_distance(df_chunk):
    df_chunk = df_chunk[df_chunk['distance'] < 101]
    return df_chunk

In [5]:
chunksize = 500000 # 5 million rows at one go. Or try 10 million

In [ ]:
df.shape

In [2]:
TRAIN_PATH = 'Data/26mln_clean.csv'

In [3]:
df = df.drop('Unnamed: 0', axis=1)

NameError: name 'df' is not defined

In [6]:
df.head()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,hour,dayofweek,month,year,distance
0,4.5,-73.844315,40.721317,-73.84161,40.712276,1,17,0,6,2009,1.030742
1,16.9,-74.016045,40.711304,-73.97927,40.782005,1,16,1,1,2010,8.450000
2,5.7,-73.982735,40.761270,-73.99124,40.750560,2,0,3,8,2011,1.389632
3,7.7,-73.987130,40.733143,-73.99157,40.758090,1,4,5,4,2012,2.799211
4,5.3,-73.968094,40.768010,-73.95666,40.783764,1,7,1,3,2010,1.999081

In [7]:
df.shape

(52878537, 11)

In [4]:
%%time
# Set columns to most suitable type to optimize for memory usage
traintypes = {'fare_amount': 'float32',
              'pickup_longitude': 'float32',
              'pickup_latitude': 'float32',
              'dropoff_longitude': 'float32',
              'dropoff_latitude': 'float32',
              'passenger_count': 'uint8',
              'hour':'uint8',
              'dayofweek':'uint8',
              'month':'uint8',
              'year':'int',
              'distance':'float32'}

cols = list(traintypes.keys())

chunksize = 1000000 # 1 million rows at one go. Or try 10 million


X_train_list = [] # list to hold the batch dataframe
X_test_list = []
y_train_list = []
y_test_list = []

for df in tqdm(pd.read_csv(TRAIN_PATH, usecols=cols, dtype=traintypes, chunksize=chunksize)):
#     df = df.drop('Unnamed: 0', axis=1)
    df = df.drop('pickup_longitude', axis=1)
    df = df.drop('pickup_latitude', axis=1)
    df = df.drop('dropoff_longitude', axis=1)
    df = df.drop('dropoff_latitude', axis=1)
    
    X = df.drop(["fare_amount"],axis=1)
    y = df.fare_amount
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.005,random_state=123)
    
    X_train_list.append(X_train)
    X_test_list.append(X_test)
    y_train_list.append(y_train)
    y_test_list.append(y_test)
    del X, y, X_train, X_test, y_train, y_test

27it [00:49,  1.96s/it]

CPU times: user 1min 13s, sys: 2.38 s, total: 1min 15s
Wall time: 50 s

In [5]:
# Merge all dataframes into one dataframe
X_train = pd.concat(X_train_list)
X_test = pd.concat(X_test_list)
y_train = pd.concat(y_train_list)
y_test = pd.concat(y_test_list)



# Delete the dataframe list to release memory
del X_train_list, X_test_list, y_train_list, y_test_list, df

In [6]:
X_train.shape

(26670328, 6)

In [7]:
y_test.shape

(134022,)

In [8]:
del df

NameError: name 'df' is not defined

In [10]:
def XGBoost(X_train,X_test,y_train,y_test,num_rounds=1000):
    dtrain = xgb.DMatrix(X_train,label=y_train)
    dtest = xgb.DMatrix(X_test,label=y_test)

    return xgb.train(params={
                    'eta':'0.3',
                    'max_depth':'8',
                    'eval_metric':'rmse',
                    'objective':'reg:linear',
                    'tree_method':'approx'}
                    ,dtrain=dtrain,num_boost_round=num_rounds, 
                    early_stopping_rounds=50,evals=[(dtest,'test')],)

In [9]:
?xgb.train()

In [12]:
xgbm = XGBoost(X_train,X_test,y_train,y_test)

[22:28:24] Tree method is selected to be 'approx'
[22:28:40] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 498 extra nodes, 0 pruned nodes, max_depth=8
[0]	test-rmse:10.4083
Will train until test-rmse hasn't improved in 50 rounds.
[22:28:53] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 504 extra nodes, 0 pruned nodes, max_depth=8
[1]	test-rmse:7.84749
[22:29:06] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 508 extra nodes, 0 pruned nodes, max_depth=8
[2]	test-rmse:6.21149
[22:29:18] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 510 extra nodes, 0 pruned nodes, max_depth=8
[3]	test-rmse:5.21877
[22:29:30] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 508 extra nodes, 0 pruned nodes, max_depth=8
[4]	test-rmse:4.65111
[22:29:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 506 extra nodes, 0 pruned nodes, max_depth=8
[5]	test-rmse:4.33947
[22:29:54] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 504 extra nodes, 0 pruned nodes, max_depth=8
[6]	test-rmse:4.17638
[22:30:06] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 510 extra nodes, 0 pruned nodes, max_depth=8
[7]	test-rmse:4.09053
[22:30:18] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 510 extra nodes, 0 pruned nodes, max_depth=8
[8]	test-rmse:4.04312
[22:30:30] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 510 extra nodes, 0 pruned nodes, max_depth=8
[9]	test-rmse:4.02022
[22:30:43] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 510 extra nodes, 0 pruned nodes, max_depth=8
[10]	test-rmse:4.00576
[22:30:55] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 506 extra nodes, 0 pruned nodes, max_depth=8
[11]	test-rmse:3.99894
[22:31:08] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 510 extra nodes, 0 pruned nodes, max_depth=8
[12]	test-rmse:3.99305
[22:31:20] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 504 extra nodes, 0 pruned nodes, max_depth=8
[13]	test-rmse:3.98993
[22:31:33] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 506 extra nodes, 0 pruned nodes, max_depth=8
[14]	test-rmse:3.98775
[22:31:45] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 508 extra nodes, 0 pruned nodes, max_depth=8
[15]	test-rmse:3.9862
[22:31:58] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 478 extra nodes, 0 pruned nodes, max_depth=8
[16]	test-rmse:3.98382
[22:32:11] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 482 extra nodes, 0 pruned nodes, max_depth=8
[17]	test-rmse:3.9827
[22:32:23] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 504 extra nodes, 0 pruned nodes, max_depth=8
[18]	test-rmse:3.98123
[22:32:36] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 476 extra nodes, 0 pruned nodes, max_depth=8
[19]	test-rmse:3.98048
[22:32:48] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 458 extra nodes, 0 pruned nodes, max_depth=8
[20]	test-rmse:3.97996
[22:33:01] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 444 extra nodes, 0 pruned nodes, max_depth=8
[21]	test-rmse:3.97859
[22:33:14] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 450 extra nodes, 0 pruned nodes, max_depth=8
[22]	test-rmse:3.97851
[22:33:26] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 454 extra nodes, 0 pruned nodes, max_depth=8
[23]	test-rmse:3.97783
[22:33:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 468 extra nodes, 0 pruned nodes, max_depth=8
[24]	test-rmse:3.97793
[22:33:52] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 504 extra nodes, 0 pruned nodes, max_depth=8
[25]	test-rmse:3.97704
[22:34:05] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 442 extra nodes, 0 pruned nodes, max_depth=8
[26]	test-rmse:3.97701
[22:34:17] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 348 extra nodes, 0 pruned nodes, max_depth=8
[27]	test-rmse:3.97723
[22:34:29] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 242 extra nodes, 0 pruned nodes, max_depth=8
[28]	test-rmse:3.97704
[22:34:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 466 extra nodes, 0 pruned nodes, max_depth=8
[29]	test-rmse:3.97683
[22:34:54] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 280 extra nodes, 0 pruned nodes, max_depth=8
[30]	test-rmse:3.97695
[22:35:06] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 276 extra nodes, 0 pruned nodes, max_depth=8
[31]	test-rmse:3.97675
[22:35:18] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 248 extra nodes, 0 pruned nodes, max_depth=8
[32]	test-rmse:3.97678
[22:35:30] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 426 extra nodes, 0 pruned nodes, max_depth=8
[33]	test-rmse:3.97607
[22:35:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 250 extra nodes, 0 pruned nodes, max_depth=8
[34]	test-rmse:3.97603
[22:35:55] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 416 extra nodes, 0 pruned nodes, max_depth=8
[35]	test-rmse:3.97585
[22:36:08] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 470 extra nodes, 0 pruned nodes, max_depth=8
[36]	test-rmse:3.97497
[22:36:20] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 150 extra nodes, 0 pruned nodes, max_depth=8
[37]	test-rmse:3.97498
[22:36:32] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 490 extra nodes, 0 pruned nodes, max_depth=8
[38]	test-rmse:3.97488
[22:36:44] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 266 extra nodes, 0 pruned nodes, max_depth=8
[39]	test-rmse:3.97483
[22:36:56] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 330 extra nodes, 0 pruned nodes, max_depth=8
[40]	test-rmse:3.97486
[22:37:09] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 404 extra nodes, 0 pruned nodes, max_depth=8
[41]	test-rmse:3.97502
[22:37:22] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 452 extra nodes, 0 pruned nodes, max_depth=8
[42]	test-rmse:3.97466
[22:37:34] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 462 extra nodes, 0 pruned nodes, max_depth=8
[43]	test-rmse:3.975
[22:37:46] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 220 extra nodes, 0 pruned nodes, max_depth=8
[44]	test-rmse:3.97498
[22:37:58] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 218 extra nodes, 0 pruned nodes, max_depth=8
[45]	test-rmse:3.97496
[22:38:10] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 94 extra nodes, 0 pruned nodes, max_depth=8
[46]	test-rmse:3.97476
[22:38:22] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 140 extra nodes, 0 pruned nodes, max_depth=8
[47]	test-rmse:3.97477
[22:38:35] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 456 extra nodes, 0 pruned nodes, max_depth=8
[48]	test-rmse:3.9747
[22:38:48] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 444 extra nodes, 0 pruned nodes, max_depth=8
[49]	test-rmse:3.97467
[22:39:00] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 320 extra nodes, 0 pruned nodes, max_depth=8
[50]	test-rmse:3.97466
[22:39:12] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 360 extra nodes, 0 pruned nodes, max_depth=8
[51]	test-rmse:3.9745
[22:39:24] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 342 extra nodes, 0 pruned nodes, max_depth=8
[52]	test-rmse:3.97445
[22:39:36] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 358 extra nodes, 0 pruned nodes, max_depth=8
[53]	test-rmse:3.97463
[22:39:48] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 324 extra nodes, 0 pruned nodes, max_depth=8
[54]	test-rmse:3.97472
[22:40:00] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 78 extra nodes, 0 pruned nodes, max_depth=8
[55]	test-rmse:3.97472

[22:40:11] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 172 extra nodes, 0 pruned nodes, max_depth=8
[56]	test-rmse:3.97469
[22:40:24] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 396 extra nodes, 0 pruned nodes, max_depth=8
[57]	test-rmse:3.97499
[22:40:36] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 440 extra nodes, 0 pruned nodes, max_depth=8
[58]	test-rmse:3.97505
[22:40:49] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 412 extra nodes, 0 pruned nodes, max_depth=8
[59]	test-rmse:3.9758
[22:41:01] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 432 extra nodes, 0 pruned nodes, max_depth=8
[60]	test-rmse:3.9757
[22:41:13] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 332 extra nodes, 0 pruned nodes, max_depth=8
[61]	test-rmse:3.97589
[22:41:25] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 336 extra nodes, 0 pruned nodes, max_depth=8
[62]	test-rmse:3.97491
[22:41:38] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 486 extra nodes, 0 pruned nodes, max_depth=8
[63]	test-rmse:3.9741
[22:41:50] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 348 extra nodes, 0 pruned nodes, max_depth=8
[64]	test-rmse:3.97417
[22:42:03] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 396 extra nodes, 0 pruned nodes, max_depth=8
[65]	test-rmse:3.97435
[22:42:15] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 286 extra nodes, 0 pruned nodes, max_depth=8
[66]	test-rmse:3.97426
[22:42:26] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 136 extra nodes, 0 pruned nodes, max_depth=8
[67]	test-rmse:3.97427
[22:42:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 338 extra nodes, 0 pruned nodes, max_depth=8
[68]	test-rmse:3.97472
[22:42:51] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 178 extra nodes, 0 pruned nodes, max_depth=8
[69]	test-rmse:3.97462
[22:43:03] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 294 extra nodes, 0 pruned nodes, max_depth=8
[70]	test-rmse:3.97464
[22:43:15] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 428 extra nodes, 0 pruned nodes, max_depth=8
[71]	test-rmse:3.97461
[22:43:27] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 170 extra nodes, 0 pruned nodes, max_depth=8
[72]	test-rmse:3.97454
[22:43:40] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 420 extra nodes, 0 pruned nodes, max_depth=8
[73]	test-rmse:3.97481
[22:43:53] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 416 extra nodes, 0 pruned nodes, max_depth=8
[74]	test-rmse:3.97476
[22:44:05] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 476 extra nodes, 0 pruned nodes, max_depth=8
[75]	test-rmse:3.97476
[22:44:17] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 348 extra nodes, 0 pruned nodes, max_depth=8
[76]	test-rmse:3.9747
[22:44:29] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 460 extra nodes, 0 pruned nodes, max_depth=8
[77]	test-rmse:3.97464
[22:44:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 436 extra nodes, 0 pruned nodes, max_depth=8
[78]	test-rmse:3.97481
[22:44:54] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 402 extra nodes, 0 pruned nodes, max_depth=8
[79]	test-rmse:3.97481
[22:45:06] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 254 extra nodes, 0 pruned nodes, max_depth=8
[80]	test-rmse:3.97476
[22:45:18] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 364 extra nodes, 0 pruned nodes, max_depth=8
[81]	test-rmse:3.97454
[22:45:31] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 358 extra nodes, 0 pruned nodes, max_depth=8
[82]	test-rmse:3.97431
[22:45:43] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 194 extra nodes, 0 pruned nodes, max_depth=8
[83]	test-rmse:3.97435
[22:45:55] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 148 extra nodes, 0 pruned nodes, max_depth=8
[84]	test-rmse:3.97436
[22:46:07] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 180 extra nodes, 0 pruned nodes, max_depth=8
[85]	test-rmse:3.97436
[22:46:18] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 130 extra nodes, 0 pruned nodes, max_depth=8
[86]	test-rmse:3.97436
[22:46:30] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 126 extra nodes, 0 pruned nodes, max_depth=8
[87]	test-rmse:3.97441
[22:46:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 278 extra nodes, 0 pruned nodes, max_depth=8
[88]	test-rmse:3.97443
[22:46:54] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 120 extra nodes, 0 pruned nodes, max_depth=8
[89]	test-rmse:3.97443
[22:47:06] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 66 extra nodes, 0 pruned nodes, max_depth=8
[90]	test-rmse:3.97436
[22:47:17] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 260 extra nodes, 0 pruned nodes, max_depth=8
[91]	test-rmse:3.97433
[22:47:30] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 408 extra nodes, 0 pruned nodes, max_depth=8
[92]	test-rmse:3.97375
[22:47:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 186 extra nodes, 0 pruned nodes, max_depth=8
[93]	test-rmse:3.97396
[22:47:54] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 388 extra nodes, 0 pruned nodes, max_depth=8
[94]	test-rmse:3.97393
[22:48:07] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 364 extra nodes, 0 pruned nodes, max_depth=8
[95]	test-rmse:3.97381
[22:48:19] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 278 extra nodes, 0 pruned nodes, max_depth=8
[96]	test-rmse:3.9737
[22:48:31] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 346 extra nodes, 0 pruned nodes, max_depth=8
[97]	test-rmse:3.97372
[22:48:42] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 250 extra nodes, 0 pruned nodes, max_depth=8
[98]	test-rmse:3.97365
[22:48:54] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 252 extra nodes, 0 pruned nodes, max_depth=8
[99]	test-rmse:3.97372
[22:49:06] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 154 extra nodes, 0 pruned nodes, max_depth=8
[100]	test-rmse:3.97377
[22:49:19] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 350 extra nodes, 0 pruned nodes, max_depth=8
[101]	test-rmse:3.97342
[22:49:31] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 462 extra nodes, 0 pruned nodes, max_depth=8
[102]	test-rmse:3.97407
[22:49:43] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 336 extra nodes, 0 pruned nodes, max_depth=8
[103]	test-rmse:3.97401
[22:49:57] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 426 extra nodes, 0 pruned nodes, max_depth=8
[104]	test-rmse:3.97372
[22:50:09] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 344 extra nodes, 0 pruned nodes, max_depth=8
[105]	test-rmse:3.97372
[22:50:21] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 162 extra nodes, 0 pruned nodes, max_depth=8
[106]	test-rmse:3.97374
[22:50:33] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 136 extra nodes, 0 pruned nodes, max_depth=8
[107]	test-rmse:3.97362
[22:50:45] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 110 extra nodes, 0 pruned nodes, max_depth=8
[108]	test-rmse:3.97392
[22:50:56] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 218 extra nodes, 0 pruned nodes, max_depth=8
[109]	test-rmse:3.97378
[22:51:08] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 240 extra nodes, 0 pruned nodes, max_depth=8
[110]	test-rmse:3.97351
[22:51:20] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 204 extra nodes, 0 pruned nodes, max_depth=8
[111]	test-rmse:3.97356

[22:51:32] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 82 extra nodes, 0 pruned nodes, max_depth=8
[112]	test-rmse:3.97353
[22:51:44] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 124 extra nodes, 0 pruned nodes, max_depth=8
[113]	test-rmse:3.97353
[22:51:57] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 368 extra nodes, 0 pruned nodes, max_depth=8
[114]	test-rmse:3.97368
[22:52:09] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 174 extra nodes, 0 pruned nodes, max_depth=8
[115]	test-rmse:3.97365
[22:52:21] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 416 extra nodes, 0 pruned nodes, max_depth=8
[116]	test-rmse:3.97359
[22:52:33] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 148 extra nodes, 0 pruned nodes, max_depth=8
[117]	test-rmse:3.97357
[22:52:45] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 178 extra nodes, 0 pruned nodes, max_depth=8
[118]	test-rmse:3.97358
[22:52:57] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 472 extra nodes, 0 pruned nodes, max_depth=8
[119]	test-rmse:3.97354
[22:53:09] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 298 extra nodes, 0 pruned nodes, max_depth=8
[120]	test-rmse:3.9735
[22:53:22] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 396 extra nodes, 0 pruned nodes, max_depth=8
[121]	test-rmse:3.97364
[22:53:34] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 214 extra nodes, 0 pruned nodes, max_depth=8
[122]	test-rmse:3.97361
[22:53:47] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 442 extra nodes, 0 pruned nodes, max_depth=8
[123]	test-rmse:3.97378
[22:53:59] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 276 extra nodes, 0 pruned nodes, max_depth=8
[124]	test-rmse:3.97372
[22:54:11] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 336 extra nodes, 0 pruned nodes, max_depth=8
[125]	test-rmse:3.97416
[22:54:24] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 416 extra nodes, 0 pruned nodes, max_depth=8
[126]	test-rmse:3.9741
[22:54:36] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 276 extra nodes, 0 pruned nodes, max_depth=8
[127]	test-rmse:3.97472
[22:54:48] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 158 extra nodes, 0 pruned nodes, max_depth=8
[128]	test-rmse:3.97462
[22:55:00] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 434 extra nodes, 0 pruned nodes, max_depth=8
[129]	test-rmse:3.97428
[22:55:12] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 260 extra nodes, 0 pruned nodes, max_depth=8
[130]	test-rmse:3.97429
[22:55:24] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 332 extra nodes, 0 pruned nodes, max_depth=8
[131]	test-rmse:3.97439
[22:55:36] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 318 extra nodes, 0 pruned nodes, max_depth=8
[132]	test-rmse:3.97437
[22:55:48] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 228 extra nodes, 0 pruned nodes, max_depth=8
[133]	test-rmse:3.9744
[22:56:00] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 188 extra nodes, 0 pruned nodes, max_depth=8
[134]	test-rmse:3.9744
[22:56:12] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 234 extra nodes, 0 pruned nodes, max_depth=8
[135]	test-rmse:3.9742
[22:56:24] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 118 extra nodes, 0 pruned nodes, max_depth=8
[136]	test-rmse:3.97419
[22:56:36] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 142 extra nodes, 0 pruned nodes, max_depth=8
[137]	test-rmse:3.97424
[22:56:48] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 468 extra nodes, 0 pruned nodes, max_depth=8
[138]	test-rmse:3.97428
[22:57:01] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 344 extra nodes, 0 pruned nodes, max_depth=8
[139]	test-rmse:3.97407
[22:57:13] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 344 extra nodes, 0 pruned nodes, max_depth=8
[140]	test-rmse:3.97408
[22:57:26] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 392 extra nodes, 0 pruned nodes, max_depth=8
[141]	test-rmse:3.97383
[22:57:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 410 extra nodes, 0 pruned nodes, max_depth=8
[142]	test-rmse:3.97378
[22:57:51] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 318 extra nodes, 0 pruned nodes, max_depth=8
[143]	test-rmse:3.97388
[22:58:03] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 196 extra nodes, 0 pruned nodes, max_depth=8
[144]	test-rmse:3.97388
[22:58:15] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 190 extra nodes, 0 pruned nodes, max_depth=8
[145]	test-rmse:3.97414
[22:58:27] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 314 extra nodes, 0 pruned nodes, max_depth=8
[146]	test-rmse:3.97427
[22:58:39] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 374 extra nodes, 0 pruned nodes, max_depth=8
[147]	test-rmse:3.97426
[22:58:52] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 452 extra nodes, 0 pruned nodes, max_depth=8
[148]	test-rmse:3.97462
[22:59:04] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 298 extra nodes, 0 pruned nodes, max_depth=8
[149]	test-rmse:3.97464
[22:59:16] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 422 extra nodes, 0 pruned nodes, max_depth=8
[150]	test-rmse:3.97433
[22:59:29] /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 306 extra nodes, 0 pruned nodes, max_depth=8
[151]	test-rmse:3.97397
Stopping. Best iteration:
[101]	test-rmse:3.97342

In [ ]:
dataset.shape

In [62]:
dataset.to_csv('24mln_taxifare.csv')

In [ ]:
dataset.head()

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24191409 entries, 0 to 24191408
Data columns (total 11 columns):
fare_amount          float64
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count      int64
dayofweek            int64
year                 int64
hour                 int64
month                int64
distance             float64
dtypes: float64(6), int64(5)
memory usage: 2.0 GB

In [4]:
dataset = dataset.drop('Unnamed: 0', axis=1)

# XGB TUNING

General Approach for Parameter Tuning
We will use an approach similar to that of GBM here. The various steps to be performed are:

1. Choose a relatively high learning rate. Generally a learning rate of 0.1 works but somewhere between 0.05 to 0.3 should work for different problems. Determine the optimum number of trees for this learning rate. XGBoost has a very useful function called as “cv” which performs cross-validation at each boosting iteration and thus returns the optimum number of trees required.
2. Tune tree-specific parameters ( max_depth, min_child_weight, gamma, subsample, colsample_bytree) for decided learning rate and number of trees. Note that we can choose different parameters to define a tree and I’ll take up an example here.
3. Tune regularization parameters (lambda, alpha) for xgboost which can help reduce model complexity and enhance performance.
4. Lower the learning rate and decide the optimal parameters.

In [12]:
#Import libraries:
import pandas as pd
import numpy as np

from xgboost.sklearn import XGBClassifier
from sklearn import cross_validation, metrics   #Additional scklearn functions
from sklearn.grid_search import GridSearchCV   #Perforing grid search

import matplotlib.pylab as plt
%matplotlib inline
from matplotlib.pylab import rcParams

In [23]:
dataset.head()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,dayofweek,year,hour,month,distance
0,4.5,-73.844315,40.721317,-73.84161,40.712276,1,0,2009,17,6,1.030742
1,16.9,-74.016045,40.711304,-73.97927,40.782005,1,1,2010,16,1,8.450000
2,5.7,-73.982735,40.761270,-73.99124,40.750560,2,3,2011,0,8,1.389632
3,7.7,-73.987130,40.733143,-73.99157,40.758090,1,5,2012,4,4,2.799211
4,5.3,-73.968094,40.768010,-73.95666,40.783764,1,1,2010,7,3,1.999081

In [14]:
# IDcol = 'ID'
# train = dataset
# target = 'fare_amount'
# predictors = dataset.drop(target, axis=1)

In [15]:
del predictors

NameError: name 'predictors' is not defined

In [34]:
def modelfit(alg, dtrain, predictors,useTrainCV=True, cv_folds=5, early_stopping_rounds=50):
    
    if useTrainCV:
        xgb_param = alg.get_xgb_params()
        xgtrain = xgb.DMatrix(dtrain[predictors].values, label=dtrain[target].values)
        cvresult = xgb.cv(xgb_param, xgtrain, num_boost_round=alg.get_params()['n_estimators'], nfold=cv_folds,
            metrics='auc', early_stopping_rounds=early_stopping_rounds)
        alg.set_params(n_estimators=cvresult.shape[0])
    
    #Fit the algorithm on the data
    alg.fit(dtrain[predictors], dtrain['fare_amount'],eval_metric='auc')
        
    #Predict training set:
    dtrain_predictions = alg.predict(dtrain[predictors])
    dtrain_predprob = alg.predict_proba(dtrain[predictors])[:,1]
        
    #Print model report:
    print("\nModel Report")
    print("Accuracy : %.4g" % metrics.accuracy_score(dtrain['fare_amount'].values, dtrain_predictions))
    print("AUC Score (Train): %f" % metrics.roc_auc_score(dtrain['fare_amount'], dtrain_predprob))
                    
    feat_imp = pd.Series(alg.booster().get_fscore()).sort_values(ascending=False)
    feat_imp.plot(kind='bar', title='Feature Importances')
    plt.ylabel('Feature Importance Score')

In [4]:
del dataset

In [3]:
dataset = pd.read_csv("24mln_taxifare.csv")
dataset = dataset.drop('Unnamed: 0', axis=1)
X = dataset.drop(["fare_amount"],axis=1)
y = dataset.fare_amount
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.005,random_state=123)

In [19]:
def XGBoost(X_train,X_test,y_train,y_test,num_rounds=500):
    dtrain = xgb.DMatrix(X_train,label=y_train)
    dtest = xgb.DMatrix(X_test,label=y_test)

    return xgb.train(
                     params={
                         'objective':'reg:linear',
                         'eval_metric':'rmse'},
                    early_stopping_rounds=20,
                    evals=[(dtest,'test')],)

In [20]:
xgbm = XGBoost(X_train,X_test,y_train,y_test)

NameError: name 'X_train' is not defined

In [36]:
xgb1 = XGBClassifier(
 learning_rate =0.1,
 n_estimators=1000,
 max_depth=5,
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'reg:logistic',
 nthread=4,
 scale_pos_weight=1,
 seed=27)

In [37]:
#xgbm = XGBoost(X_train,X_test,y_train,y_test)
predictors = dataset.drop(target, axis=1)

In [ ]:
modelfit(xgb1, dataset, predictors)

In [30]:
type(dataset)

pandas.core.frame.DataFrame

In [7]:
from sklearn.externals import joblib

In [8]:
joblib.dump(xgbm, 'taxi_fare_xgboost_3.9.pkl.pkl')

NameError: name 'xgbm' is not defined

In [10]:
test_1 = pd.read_csv('taxi_fare_test_file.csv')

In [12]:
xgbm_pred = xgbm.predict(xgb.DMatrix(test_1), ntree_limit = xgbm.best_ntree_limit)

ValueError: feature_names mismatch: ['Unnamed: 0', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count', 'dayofweek', 'hour', 'month', 'distance'] ['Unnamed: 0', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count', 'dayofweek', 'year', 'hour', 'distance']
expected month in input data
training data did not have the following fields: year

In [17]:
test_1 = test_1.drop('Unnamed: 0', axis=1)

KeyError: "labels ['Unnamed: 0'] not contained in axis"

In [20]:
dataset

,Unnamed: 0,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,dayofweek,hour,month,distance
0,0,4.50,-73.844315,40.721317,-73.841610,40.712276,1,0,17,6,1.030742
1,1,16.90,-74.016045,40.711304,-73.979270,40.782005,1,1,16,1,8.450000
2,2,5.70,-73.982735,40.761270,-73.991240,40.750560,2,3,0,8,1.389632
3,3,7.70,-73.987130,40.733143,-73.991570,40.758090,1,5,4,4,2.799211
4,4,5.30,-73.968094,40.768010,-73.956660,40.783764,1,1,7,3,1.999081
5,5,12.10,-74.000960,40.731630,-73.972890,40.758232,1,3,9,1,3.787118
6,6,7.50,-73.980000,40.751663,-73.973800,40.764843,1,1,20,11,1.555860
7,7,16.50,-73.951300,40.774140,-73.990100,40.751050,1,2,17,1,4.155500
8,8,9.00,-74.006460,40.726710,-73.993080,40.731630,1,0,13,12,1.253181
9,9,8.90,-73.980660,40.733870,-73.991540,40.758137,2,2,1,9,2.849590
10,10,5.30,-73.996340,40.737140,-73.980720,40.733560,1,6,7,4,1.374817
11,12,4.10,-73.991600,40.744713,-73.983080,40.744682,2,4,1,11,0.717939
12,13,7.00,-74.005360,40.728867,-74.008910,40.710907,1,1,19,7,2.019273
13,14,7.70,-74.001820,40.737550,-73.998060,40.722790,2,1,17,4,1.671456
14,16,12.50,-73.986430,40.760464,-73.988990,40.737076,1,2,7,2,2.609567
15,17,5.30,-73.981060,40.737690,-73.994180,40.728413,1,2,16,7,1.512197
16,18,5.30,-73.969505,40.784843,-73.958730,40.783356,1,2,14,7,0.921962
17,19,4.00,-73.979810,40.751904,-73.979450,40.755480,1,5,20,12,0.399070
18,20,10.50,-73.985380,40.747856,-73.978380,40.762070,1,1,13,9,1.686988
19,21,11.50,-73.957954,40.779250,-73.961250,40.758785,1,1,12,2,2.292563
20,22,4.50,-73.991710,40.770504,-73.985460,40.763670,1,3,18,8,0.924147
21,23,4.90,-74.000630,40.747475,-73.986670,40.740578,1,0,12,12,1.404144
22,24,6.10,-73.969620,40.756973,-73.981155,40.759712,1,3,15,12,1.018225
23,25,7.30,-73.991875,40.754436,-73.977230,40.774323,3,1,16,6,2.532089
24,27,4.50,-73.988890,40.760160,-73.986440,40.757860,3,1,19,6,0.328589
25,28,9.30,-73.989260,40.690834,-74.004135,40.725690,1,4,6,5,4.073512
26,29,4.50,-73.981020,40.737760,-73.980670,40.730495,2,6,0,8,0.808170
27,30,5.50,-73.976074,40.752422,-73.981080,40.759285,1,2,16,2,0.871792
28,31,22.54,-74.010480,40.717667,-73.985770,40.660366,1,6,21,6,6.703551
29,32,31.90,-73.873024,40.773884,-73.984540,40.769547,3,4,16,1,9.403364
...,...,...,...,...,...,...,...,...,...,...,...
19352859,19999969,5.50,-73.986920,40.766590,-73.999016,40.760670,1,6,4,8,1.212684
19352860,19999970,7.50,-73.988170,40.745804,-73.969730,40.750650,1,2,3,5,1.644156
19352861,19999971,7.50,-73.989640,40.734116,-73.994990,40.745260,1,2,19,4,1.318404
19352862,19999972,19.00,-73.970894,40.788628,-73.919590,40.823450,1,3,1,7,5.799503
19352863,19999973,7.00,-73.983430,40.730140,-73.993210,40.724530,3,3,20,4,1.033745
19352864,19999974,10.50,-73.981285,40.737312,-73.985794,40.765300,1,5,1,3,3.135263
19352865,19999975,11.70,-73.982254,40.782967,-73.985690,40.742176,2,5,18,7,4.544910
19352866,19999976,10.10,-73.969795,40.757423,-73.972855,40.792713,2,2,1,6,3.932490
19352867,19999977,7.70,-73.960350,40.775837,-73.951805,40.798042,1,3,17,11,2.571790
19352868,19999978,7.50,-73.980360,40.738613,-73.976170,40.723724,1,4,22,5,1.692756
19352869,19999979,18.10,-73.994150,40.751217,-73.912670,40.778160,1,5,6,5,7.487788
19352870,19999980,9.70,-73.970240,40.760895,-73.988625,40.753910,1,1,11,6,1.732524
19352871,19999982,5.30,-73.970230,40.794456,-73.965385,40.808800,1,1,18,10,1.646204
19352872,19999983,4.50,-73.950386,40.771587,-73.958240,40.771378,1,0,19,2,0.661516
19352873,19999984,45.33,-73.983765,40.758020,-73.864130,40.769592,2,0,14,2,10.157632
19352874,19999985,9.70,-73.980590,40.742700,-73.991650,40.764736,5,6,2,12,2.621653
19352875,19999986,5.70,-73.982170,40.776527,-73.979880,40.788055,5,0,4,12,1.296262
19352876,19999987,12.00,-73.983090,40.693310,-74.008830,40.707170,1,3,13,1,2.661012
19352877,19999988,3.50,-73.991550,40.759758,-73.992950,40.755340,5,4,14,9,0.505225
19352878,19999989,9.00,-73.972670,40.785950,-73.975310,40.760998,1,6,9,5,2.783419
19352879,19999990,8.00,-74.009056,40.738180,-73.983925,40.738277,2,5,3,11,2.117392
19352880,19999991,9.30,-73.986320,40.761288,-73.994200,40.751053,1,3,17,5,1.317517
19352881,19999992,6.90,-73.974434,40.762410,-73.987686,40.750175,2,2,19,7,1.759677
19352882,19999993,12.50,-74.002810,40.728687,-73.955880,40.774597,1,0,21,7,6.456540
19352883,19999994,6.10,-73.994770,40.740154,-74.008220,40.736320,1,6,19,8,1.210774
19352884,19999995,9.50,-73.977710,40.776920,-73.966866,40.772446,5,2,17,10,1.039696
19352885,19999996,3.50,-73.963240,40.766754,-73.965500,40.763580,1,4,0,8,0.400899
19352886,19999997,4.90,-73.970950,40.794277,-73.961380,40.801376,1,5,22,10,1.127701
19352887,19999998,5.50,-73.968080,40.799800,-73.961060,40.811672,6,2,12,12,1.446200
19352888,19999999,10.90,-74.001990,40.734950,-74.003750,40.722210,5,4,14,8,1.424507

In [18]:
test_1

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,dayofweek,year,hour,distance
0,-73.973320,40.763805,-73.981430,40.743835,1,1,2015,13,2.323260
1,-73.986860,40.719383,-73.998886,40.739200,1,1,2015,13,2.425353
2,-73.982520,40.751260,-73.979650,40.746140,1,5,2011,11,0.618412
3,-73.981160,40.767807,-73.990450,40.751637,1,5,2012,21,1.960778
4,-73.966050,40.789776,-73.988560,40.744427,1,5,2012,21,5.387280
5,-73.960980,40.765550,-73.979180,40.740050,1,5,2012,21,3.222969
6,-73.949010,40.773205,-73.959625,40.770893,1,3,2011,12,0.929905
7,-73.777280,40.646637,-73.985085,40.759370,1,3,2011,12,21.540153
8,-74.014100,40.709637,-73.995110,40.741364,1,3,2011,12,3.873826
9,-73.969580,40.765520,-73.980680,40.770725,1,1,2014,15,1.099625
10,-73.989370,40.741974,-73.999300,40.722534,1,1,2014,15,2.317753
11,-74.001620,40.740894,-73.956390,40.767437,1,1,2014,15,4.819091
12,-73.991196,40.739937,-73.997170,40.735268,1,0,2010,20,0.723106
13,-73.982030,40.762722,-74.001870,40.761543,1,0,2010,20,1.675797
14,-73.992455,40.728703,-73.983400,40.750150,1,3,2011,3,2.503796
15,-73.983580,40.746994,-73.951180,40.785904,1,3,2011,3,5.115234
16,-74.006744,40.731720,-74.010200,40.732320,1,6,2012,16,0.298730
17,-73.976450,40.785600,-73.952220,40.772120,1,6,2012,16,2.531505
18,-73.973550,40.763348,-73.972100,40.756416,1,6,2012,16,0.780336
19,-73.970920,40.756023,-73.975950,40.755560,1,6,2012,16,0.427226
20,-73.926070,40.705868,-73.941740,40.714790,1,2,2014,2,1.651970
21,-73.970560,40.764700,-73.949135,40.771800,1,5,2014,13,1.969288
22,-73.989105,40.736360,-73.992770,40.747770,1,5,2014,13,1.305682
23,-74.003525,40.748480,-73.991520,40.762960,1,5,2014,13,1.900813
24,-73.990350,40.759990,-74.015660,40.711680,1,5,2014,13,5.779692
25,-73.989480,40.757450,-74.000850,40.762707,1,5,2014,13,1.121768
26,-73.870790,40.773724,-73.741920,40.689945,1,5,2014,13,14.306966
27,-73.992680,40.733875,-73.938850,40.808220,1,5,2014,13,9.428151
28,-73.954020,40.778706,-73.950280,40.768810,1,5,2014,13,1.144457
29,-73.972740,40.743430,-74.007126,40.710194,1,5,2014,13,4.696288
...,...,...,...,...,...,...,...,...,...
9884,-73.790020,40.643818,-73.735690,40.773400,6,2,2013,22,15.119194
9885,-74.007880,40.722763,-73.965740,40.754505,6,2,2013,22,5.006573
9886,-73.978850,40.752840,-73.941154,40.812720,6,2,2013,22,7.376450
9887,-73.959080,40.783283,-73.978806,40.785656,6,2,2013,22,1.681297
9888,-73.956490,40.767513,-73.956490,40.767513,6,2,2013,22,0.000000
9889,-73.966650,40.714676,-73.971910,40.693670,6,2,2013,22,2.377588
9890,-73.976600,40.754150,-73.993290,40.730890,6,2,2013,22,2.944214
9891,-73.987180,40.760506,-73.938750,40.799507,6,2,2013,22,5.952876
9892,-73.969180,40.757770,-73.952320,40.781030,6,2,2013,22,2.950347
9893,-73.949650,40.796196,-73.911760,40.827670,6,2,2013,22,4.734996
9894,-74.002266,40.730415,-73.990360,40.756805,6,2,2013,22,3.101226
9895,-73.985840,40.731167,-73.953880,40.653940,6,2,2013,22,9.000234
9896,-73.955490,40.776863,-73.982160,40.769302,6,2,2013,22,2.398218
9897,-73.965780,40.805540,-73.982380,40.761600,6,4,2015,11,5.081663
9898,-73.979040,40.777515,-73.983660,40.781082,6,0,2015,15,0.555287
9899,-73.983240,40.764874,-73.922930,40.743458,6,6,2015,0,5.610506
9900,-73.962950,40.772480,-73.976050,40.786290,6,6,2015,21,1.890608
9901,-73.977940,40.762753,-73.976220,40.776450,6,4,2015,11,1.530118
9902,-73.905525,40.752655,-73.864150,40.737090,6,3,2015,1,3.891525
9903,-73.988400,40.738730,-73.992340,40.759193,6,4,2015,10,2.299316
9904,-73.776850,40.645035,-73.955460,40.652460,6,1,2015,20,15.091263
9905,-73.989650,40.767406,-73.941180,40.845695,6,4,2015,19,9.613797
9906,-73.988050,40.720776,-73.991040,40.718346,6,0,2015,1,0.369506
9907,-73.863460,40.769610,-73.980995,40.763240,6,1,2015,9,9.923999
9908,-73.987970,40.718920,-73.982124,40.732956,6,1,2015,13,1.636402
9909,-73.968124,40.796997,-73.955640,40.780388,6,6,2015,12,2.124874
9910,-73.945510,40.803600,-73.960210,40.776370,6,0,2015,17,3.270969
9911,-73.991600,40.726610,-73.789740,40.647010,6,6,2015,20,19.183941
9912,-73.985570,40.735430,-73.939180,40.801730,6,5,2015,1,8.343486
9913,-73.988020,40.754070,-74.000280,40.759220,6,6,2015,14,1.180825

In [19]:
xgbm_pred = xgbm.predict(xgb.DMatrix(test_1), ntree_limit = xgbm.best_ntree_limit)

ValueError: feature_names mismatch: ['Unnamed: 0', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count', 'dayofweek', 'hour', 'month', 'distance'] ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count', 'dayofweek', 'year', 'hour', 'distance']
expected Unnamed: 0, month in input data
training data did not have the following fields: year

In [132]:
submision = pd.DataFrame(xgbm_pred)

In [133]:
submision.to_csv('submission_kaggle.csv')

In [ ]:
submision['key'] = test_1['']

In [136]:
TEST_PATH

'Data/test.csv'

In [137]:
TEST_PATH = 'Data/test.csv'

In [138]:
test_join = pd.read_csv(TEST_PATH)

In [141]:
submision['key'] = test_join['key']

In [143]:
submision.to_csv('submission_kaggle.csv')

In [3]:
TRAIN_PATH = 'Data/54mln_clean.csv'

In [4]:
siema = pd.read_csv(TRAIN_PATH, nrows=200000)

In [5]:
siema

,Unnamed: 0,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,hour,dayofweek,month,year,distance
0,0,4.500000,2009-06-15 17:26:00,-73.844315,40.721317,-73.841614,40.712276,1,17,0,6,2009,1.030742
1,1,16.900000,2010-01-05 16:52:00,-74.016045,40.711304,-73.979271,40.782005,1,16,1,1,2010,8.450000
2,2,5.700000,2011-08-18 00:35:00,-73.982735,40.761269,-73.991241,40.750561,2,0,3,8,2011,1.389632
3,3,7.700000,2012-04-21 04:30:00,-73.987129,40.733143,-73.991570,40.758091,1,4,5,4,2012,2.799211
4,4,5.300000,2010-03-09 07:51:00,-73.968094,40.768009,-73.956657,40.783764,1,7,1,3,2010,1.999081
5,5,12.100000,2011-01-06 09:50:00,-74.000961,40.731628,-73.972893,40.758232,1,9,3,1,2011,3.787118
6,6,7.500000,2012-11-20 20:35:00,-73.980003,40.751663,-73.973801,40.764843,1,20,1,11,2012,1.555860
7,7,16.500000,2012-01-04 17:22:00,-73.951302,40.774139,-73.990097,40.751049,1,17,2,1,2012,4.155500
8,8,9.000000,2012-12-03 13:10:00,-74.006462,40.726711,-73.993080,40.731628,1,13,0,12,2012,1.253181
9,9,8.900000,2009-09-02 01:11:00,-73.980659,40.733871,-73.991539,40.758137,2,1,2,9,2009,2.849590
10,10,5.300000,2012-04-08 07:30:00,-73.996338,40.737141,-73.980721,40.733559,1,7,6,4,2012,1.374817
11,12,4.100000,2009-11-06 01:04:00,-73.991600,40.744713,-73.983078,40.744682,2,1,4,11,2009,0.717939
12,13,7.000000,2013-07-02 19:54:00,-74.005363,40.728867,-74.008911,40.710907,1,19,1,7,2013,2.019273
13,14,7.700000,2011-04-05 17:11:00,-74.001823,40.737549,-73.998062,40.722790,2,17,1,4,2011,1.671456
14,16,12.500000,2014-02-19 07:22:00,-73.986427,40.760464,-73.988991,40.737076,1,7,2,2,2014,2.609567
15,17,5.300000,2009-07-22 16:08:00,-73.981056,40.737690,-73.994179,40.728413,1,16,2,7,2009,1.512197
16,18,5.300000,2010-07-07 14:52:00,-73.969505,40.784843,-73.958733,40.783356,1,14,2,7,2010,0.921962
17,19,4.000000,2014-12-06 20:36:00,-73.979813,40.751904,-73.979446,40.755482,1,20,5,12,2014,0.399070
18,20,10.500000,2010-09-07 13:18:00,-73.985382,40.747856,-73.978378,40.762070,1,13,1,9,2010,1.686988
19,21,11.500000,2013-02-12 12:15:00,-73.957954,40.779251,-73.961250,40.758785,1,12,1,2,2013,2.292563
20,22,4.500000,2009-08-06 18:17:00,-73.991707,40.770504,-73.985458,40.763672,1,18,3,8,2009,0.924147
21,23,4.900000,2010-12-06 12:29:00,-74.000633,40.747475,-73.986671,40.740578,1,12,0,12,2010,1.404144
22,24,6.100000,2009-12-10 15:37:00,-73.969620,40.756973,-73.981155,40.759712,1,15,3,12,2009,1.018225
23,25,7.300000,2011-06-21 16:15:00,-73.991875,40.754436,-73.977226,40.774323,3,16,1,6,2011,2.532089
24,27,4.500000,2011-06-28 19:47:00,-73.988892,40.760159,-73.986443,40.757858,3,19,1,6,2011,0.328589
25,28,9.300000,2012-05-04 06:11:00,-73.989258,40.690834,-74.004135,40.725689,1,6,4,5,2012,4.073512
26,29,4.500000,2013-08-11 00:52:00,-73.981018,40.737759,-73.980667,40.730495,2,0,6,8,2013,0.808170
27,30,5.500000,2014-02-19 16:03:00,-73.976074,40.752422,-73.981079,40.759285,1,16,2,2,2014,0.871792
28,31,22.540001,2015-06-21 21:46:00,-74.010483,40.717667,-73.985771,40.660366,1,21,6,6,2015,6.703551
29,32,31.900000,2009-01-09 16:10:00,-73.873024,40.773884,-73.984543,40.769547,3,16,4,1,2009,9.403364
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199970,205081,9.300000,2012-06-25 09:14:00,-73.966812,40.753281,-73.982590,40.763462,1,9,0,6,2012,1.745756
199971,205082,17.000000,2013-01-02 08:55:00,-73.979805,40.744759,-74.011581,40.703999,1,8,2,1,2013,5.264258
199972,205083,3.700000,2010-04-11 04:21:00,-73.987900,40.667267,-73.982399,40.673954,2,4,6,4,2010,0.876434
199973,205084,12.900000,2011-06-30 09:11:00,-73.994194,40.751419,-73.995331,40.728962,1,9,3,6,2011,2.498954
199974,205086,3.500000,2014-08-09 04:15:00,-73.846603,40.727047,-73.844810,40.722088,1,4,5,8,2014,0.571751
199975,205087,4.200000,2009-01-17 20:16:00,-73.993027,40.730057,-73.998543,40.732208,1,20,5,1,2009,0.522745
199976,205089,10.500000,2011-11-22 16:37:00,-73.996063,40.725014,-73.974297,40.750397,2,16,1,11,2011,3.365931
199977,205090,7.300000,2010-05-06 23:10:00,-73.998329,40.751698,-73.995865,40.746098,5,23,3,5,2010,0.656380
199978,205091,7.500000,2013-08-10 09:13:00,-73.947998,40.779381,-73.954529,40.764057,2,9,5,8,2013,1.790464
199979,205092,5.500000,2013-12-14 22:26:00,-73.966599,40.804012,-73.956230,40.799877,2,22,5,12,2013,0.986439
199980,205093,6.900000,2009-05-03 14:18:00,-73.981216,40.769234,-73.976151,40.762016,3,14,6,5,2009,0.908895
199981,205094,4.500000,2010-03-28 02:41:00,-73.989502,40.719086,-73.987259,40.729153,2,2,6,3,2010,1.135245
199982,205095,12.100000,2011-03-18 23:54:00,-73.992973,40.732349,-73.958954,40.775829,1,23,4,3,2011,5.620148
199983,205096,11.700000,2009-02-03 07:46:00,-73.962517,40.799892,-73.997292,40.756283,1,7,1,2,2009,5.664644
199984,205097,7.700000,2011-06-12 12:45:00,-73.989227,40.757679,-73.982422,40.749088,2,12,6,6,2011,1.114044
199985,205098,17.000000,2015-06-03 19:01:00,-73.982727,40.769207,-73.973969,40.750889,1,19,2,6,2015,2.166355
199986,205099,3.500000,2015-06-30 20:48:00,-73.994736,40.740273,-73.991447,40.744755,1,20,1,6,2015,0.570221
199987,205100,6.900000,2009-08-28 00:16:00,-73.989075,40.741257,-73.999924,40.728783,1,0,4,8,2009,1.661170
199988,205101,10.100000,2011-05-28 21:10:00,-74.005112,40.740673,-74.007790,40.705425,1,21,5,5,2011,3.925868
199989,205102,6.500000,2012-03-07 09:42:00,-73.965652,40.754452,-73.978043,40.761139,1,9,2,3,2012,1.281402
199990,205103,10.500000,2012-10-07 18:54:00,-74.005295,40.709358,-74.008514,40.720142,1,18,6,10,2012,1.229462
199991,205104,6.500000,2014-02-22 13:40:00,-73.990509,40.737198,-74.006218,40.743862,1,13,5,2,2014,1.516805
199992,205105,4.900000,2010-02-24 07:51:00,-73.981987,40.763016,-73.979858,40.754738,1,7,2,2,2010,0.937757
199993,205106,5.500000,2015-03-23 23:36:00,-73.939919,40.708290,-73.935242,40.696850,2,23,0,3,2015,1.331791
199994,205107,4.500000,2015-03-14 09:10:00,-73.963417,40.762138,-73.969612,40.766376,1,9,5,3,2015,0.703066
199995,205108,9.000000,2013-06-01 07:36:00,-74.000015,40.737930,-74.000839,40.758251,1,7,5,6,2013,2.260646
199996,205109,21.000000,2014-04-24 10:43:00,-73.978783,40.782406,-73.992767,40.737354,1,10,3,4,2014,5.146115
199997,205110,9.300000,2011-06-05 13:40:00,-73.979492,40.746212,-73.988266,40.724045,1,13,6,6,2011,2.573349
199998,205111,7.500000,2012-12-25 12:43:00,-73.989922,40.735226,-73.973686,40.751892,6,12,1,12,2012,2.303298
199999,205112,23.700001,2009-08-21 09:23:00,-73.959038,40.762783,-73.972649,40.698009,1,9,4,8,2009,7.293231

In [12]:
def proba():
     return 1,2,3

In [13]:
a,b,c = proba()

In [14]:
a

1

In [15]:
b

2

In [16]:
c

3

In [17]:
for siema in (1,2,3,4,0.3):
    print(siema)

1
2
3
4
0.3